name: coffee_dw
version: "1.0.0"
config-version: 2

profile: coffee_dw

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  coffee_dw:
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table
