coffee_dw:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: coffee_user
      password: coffee_password
      port: 5433
      dbname: coffee_dw
      schema: silver
      threads: 4

    airflow:
      type: postgres
      host: postgres
      user: coffee_user
      password: coffee_password
      port: 5432
      dbname: coffee_dw
      schema: silver
      threads: 4
